name: LogPush Workflow

on:
  - push
  - pull_request

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date >> ./push.log
      - run: git config --local user.name  ${{ github.actor }}
      - run: git add .
      - run: git commit -m 'log push'
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
