# TASK 3

name: LogPush Workflow

on:
  - push
  - pull_request

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: date >> push.log;git config --global user.name ${GITHUB_ACTOR}; git add push.log; git commit -m '"log push"';git push
