# TASK 3

name: LogPush Workflow

on:
  - push
  - pull_request

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: date >> push.log
      - run: git config --global user.name ${GITHUB_ACTOR}
      - run: git config --global user.email "malov-tarasov@gmail.com"
      - run: git add ${GITHUB_WORKSPACE}/push.log
      - run: git commit -m '"log push"'
      - run: git push
