# TASK 3

name: LogPush Workflow

on:
  - push
  - pull_request

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
        with:
          fetch-depth: 0
      - run: date -u >> push.log
      - run: git config --global user.name ${GITHUB_ACTOR}
      - run: git add . && git commit -m "log push" && git push
